server:
  port: 8092
spring:
  datasource:
    password: 1234
    url: jdbc:mysql://localhost:3306/javacamp?useUnicode=true&characterEncoding=utf8
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
dubbo:
  application:
    name: provider-b
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 28091

mybatis:
  type-aliases-package: com.geek.dal.dao
  mapper-locations: classpath*:/mybatis/*.xml
